export const ActionTypes = {
  EMOJIS_LOAD_INITIAL_DATA: 'EMOJIS_LOAD_INITIAL_DATA',
  EMOJIS_FILTER: 'EMOJIS_FILTER',
  EMOJIS_LOAD_MORE: 'EMOJIS_LOAD_MORE',
  CATEGORIES_LOAD_INITIAL_DATA: 'CATEGORIES_LOAD_INITIAL_DATA',
  CATEGORY_SELECT: 'CATEGORY_SELECT',
  CATEGORY_DESELECT: 'CATEGORY_DESELECT',
  KEYWORD_UPDATE: 'CURRENT_KEYWORD_UPDATE',
  KEYWORD_RESET: 'CURRENT_KEYWORD_RESET'
}